apiVersion: v1
kind: ConfigMap
metadata:
  name: config-airflow
data:
  EXECUTOR: Celery
  POSTGRES_USER: airflow
  POSTGRES_DB: airflow
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  FLOWER_PORT: "5555"
  {{- if .Values.fernetKey }}
  FERNET_KEY: {{ .Values.fernetKey }}
  {{- end }}
  AIRFLOW__CORE__DAGS_FOLDER: {{ .Values.airflow.dagsFolder }}
  AIRFLOW__CORE__PLUGINS_FOLDER: {{ .Values.airflow.pluginsFolder }}
  AIRFLOW__CORE__LOAD_EXAMPLES: "0"
